namespace Shared
{
    public enum SkillId
    {
        Unknown,
        AutoAttack,
        PlaceWarp,
        BasicSkill,
        PlayDead,
        FirstAid,
        // Swordman
        Bash = 10,
        MagnumBreak,
        OneHandSwordMastery,
        TwoHandSwordMastery,
        IncHpRecovery,
        Provoke,
        Endure,
        AutoBerserk,
        HpRecWhileMoving,
        FatalBlow,
        // Mage
        FireBolt = 30,
        FireBall,
        Sight,
        FireWall,
        LightningBolt,
        Thunderstorm,
        ColdBolt,
        FrostDiver,
        NapalmBeat,
        SoulStrike,
        SafetyWall,
        StoneCurse,
        IncSpRecovery,
        EnergyCoat,
        // Archer
        OwlEye = 50,
        VultureEye,
        ImproveConcentration,
        DoubleStrafe,
        ArrowShower,
        ArrowCrafting,
        ArrowRepel,
        // Merchant
        EnlargeWeightLimit = 70,
        Discount,
        Overcharge,
        Pushcart,
        Vending,
        Mammonite,
        Identify,
        ChangeCart,
        CartRevolution,
        CrazyUproar,
        // Thief
        DoubleAttack = 90,
        ImproveDodge,
        Steal,
        Hiding,
        Envenom,
        Detoxify,
        SandAttack,
        FindStone,
        ThrowStone,
        Backslide,
        // Acolyte
        Ruwach = 110,
        Teleport,
        WarpPortal,
        Pneuma,
        DemonBane,
        DivineProtection,
        SignumCrucis,
        Angelus,
        Blessing,
        AquaBenedicta,
        Heal,
        Cure,
        IncreaseAgi,
        DecreaseAgi,
        HolyLight,

        ALL_EXCEPT_AUTO,
    }
}
