namespace Shared
{
    public enum SkillId
    {
        Unknown,
        AutoAttack,
        PlaceWarp,
        BasicSkill,
        PlayDead,
        FirstAid,
        // Swordman
        Bash = 10,
        MagnumBreak,
        OneHandSwordMastery,
        TwoHandSwordMastery,
        IncHpRecovery,
        Provoke,
        Endure,
        AutoBerserk,
        HpRecWhileMoving,
        FatalBlow,
        // Mage
        FireBolt = 30,
        FireBall,
        Sight,
        FireWall,
        LightningBolt,
        Thunderstorm,
        ColdBolt,
        FrostDiver,
        NapalmBeat,
        SoulStrike,
        SafetyWall,
        StoneCurse,
        IncSpRecovery,
        EnergyCoat,
        // Archer
        OwlEye = 50,
        VultureEye,
        ImproveConcentration,
        DoubleStrafe,
        ArrowShower,
        ArrowCrafting,
        ArrowRepel,
        // Merchant
        EnlargeWeightLimit = 70,
        Discount,
        Overcharge,
        Pushcart,
        Vending,
        Mammonite,
        Identify,
        ChangeCart,
        CartRevolution,
        CrazyUproar,
        // Thief
        DoubleAttack = 90,
        ImproveDodge,
        Steal,
        Hiding,
        Envenom,
        Detoxify,
        SandAttack,
        FindStone,
        ThrowStone,
        Backslide,
        // Acolyte
        Ruwach = 110,
        Teleport,
        WarpPortal,
        Pneuma,
        DemonBane,
        DivineProtection,
        SignumCrucis,
        Angelus,
        Blessing,
        AquaBenedicta,
        Heal,
        Cure,
        IncreaseAgi,
        DecreaseAgi,
        HolyLight,

        ALL_EXCEPT_AUTO,
        END
    }

    public static class SkillIdExtension
    {
        public static LocalizedStringId LocalizedName(this SkillId skillId)
        {
            return skillId switch
            {
                SkillId.AutoAttack => new LocalizedStringId(7),
                SkillId.PlaceWarp => new LocalizedStringId(5),
                SkillId.BasicSkill => new LocalizedStringId(9),
                SkillId.PlayDead => new LocalizedStringId(11),
                SkillId.FirstAid => new LocalizedStringId(13),
                SkillId.Bash => new LocalizedStringId(15),
                SkillId.MagnumBreak => new LocalizedStringId(17),
                SkillId.OneHandSwordMastery => new LocalizedStringId(19),
                SkillId.TwoHandSwordMastery => new LocalizedStringId(21),
                SkillId.IncHpRecovery => new LocalizedStringId(23),
                SkillId.Provoke => new LocalizedStringId(25),
                SkillId.Endure => new LocalizedStringId(27),
                SkillId.AutoBerserk => new LocalizedStringId(29),
                SkillId.HpRecWhileMoving => new LocalizedStringId(31),
                SkillId.FatalBlow => new LocalizedStringId(33),
                SkillId.FireBolt => new LocalizedStringId(35),
                SkillId.FireBall => new LocalizedStringId(37),
                SkillId.Sight => new LocalizedStringId(39),
                SkillId.FireWall => new LocalizedStringId(41),
                SkillId.LightningBolt => new LocalizedStringId(43),
                SkillId.Thunderstorm => new LocalizedStringId(45),
                SkillId.ColdBolt => new LocalizedStringId(47),
                SkillId.FrostDiver => new LocalizedStringId(49),
                SkillId.NapalmBeat => new LocalizedStringId(51),
                SkillId.SoulStrike => new LocalizedStringId(53),
                SkillId.SafetyWall => new LocalizedStringId(55),
                SkillId.StoneCurse => new LocalizedStringId(57),
                SkillId.IncSpRecovery => new LocalizedStringId(59),
                SkillId.EnergyCoat => new LocalizedStringId(61),
                SkillId.OwlEye => new LocalizedStringId(63),
                SkillId.VultureEye => new LocalizedStringId(65),
                SkillId.ImproveConcentration => new LocalizedStringId(67),
                SkillId.DoubleStrafe => new LocalizedStringId(69),
                SkillId.ArrowShower => new LocalizedStringId(71),
                SkillId.ArrowCrafting => new LocalizedStringId(73),
                SkillId.ArrowRepel => new LocalizedStringId(75),
                SkillId.EnlargeWeightLimit => new LocalizedStringId(77),
                SkillId.Discount => new LocalizedStringId(79),
                SkillId.Overcharge => new LocalizedStringId(81),
                SkillId.Pushcart => new LocalizedStringId(83),
                SkillId.Vending => new LocalizedStringId(85),
                SkillId.Mammonite => new LocalizedStringId(87),
                SkillId.Identify => new LocalizedStringId(89),
                SkillId.ChangeCart => new LocalizedStringId(91),
                SkillId.CartRevolution => new LocalizedStringId(93),
                SkillId.CrazyUproar => new LocalizedStringId(95),
                SkillId.DoubleAttack => new LocalizedStringId(97),
                SkillId.ImproveDodge => new LocalizedStringId(99),
                SkillId.Steal => new LocalizedStringId(101),
                SkillId.Hiding => new LocalizedStringId(103),
                SkillId.Envenom => new LocalizedStringId(105),
                SkillId.Detoxify => new LocalizedStringId(107),
                SkillId.SandAttack => new LocalizedStringId(109),
                SkillId.FindStone => new LocalizedStringId(111),
                SkillId.ThrowStone => new LocalizedStringId(113),
                SkillId.Backslide => new LocalizedStringId(115),
                SkillId.Ruwach => new LocalizedStringId(117),
                SkillId.Teleport => new LocalizedStringId(119),
                SkillId.WarpPortal => new LocalizedStringId(121),
                SkillId.Pneuma => new LocalizedStringId(123),
                SkillId.DemonBane => new LocalizedStringId(125),
                SkillId.DivineProtection => new LocalizedStringId(127),
                SkillId.SignumCrucis => new LocalizedStringId(129),
                SkillId.Angelus => new LocalizedStringId(131),
                SkillId.Blessing => new LocalizedStringId(133),
                SkillId.AquaBenedicta => new LocalizedStringId(135),
                SkillId.Heal => new LocalizedStringId(137),
                SkillId.Cure => new LocalizedStringId(139),
                SkillId.IncreaseAgi => new LocalizedStringId(141),
                SkillId.DecreaseAgi => new LocalizedStringId(143),
                SkillId.HolyLight => new LocalizedStringId(145),
                _ => LocalizedStringId.INVALID,
            };
        }

        public static LocalizedStringId LocalizedDescription(this SkillId skillId)
        {
            return skillId switch
            {
                SkillId.AutoAttack => new LocalizedStringId(8),
                SkillId.PlaceWarp => new LocalizedStringId(6),
                SkillId.BasicSkill => new LocalizedStringId(10),
                SkillId.PlayDead => new LocalizedStringId(12),
                SkillId.FirstAid => new LocalizedStringId(14),
                SkillId.Bash => new LocalizedStringId(16),
                SkillId.MagnumBreak => new LocalizedStringId(18),
                SkillId.OneHandSwordMastery => new LocalizedStringId(20),
                SkillId.TwoHandSwordMastery => new LocalizedStringId(22),
                SkillId.IncHpRecovery => new LocalizedStringId(24),
                SkillId.Provoke => new LocalizedStringId(26),
                SkillId.Endure => new LocalizedStringId(28),
                SkillId.AutoBerserk => new LocalizedStringId(30),
                SkillId.HpRecWhileMoving => new LocalizedStringId(32),
                SkillId.FatalBlow => new LocalizedStringId(34),
                SkillId.FireBolt => new LocalizedStringId(36),
                SkillId.FireBall => new LocalizedStringId(38),
                SkillId.Sight => new LocalizedStringId(40),
                SkillId.FireWall => new LocalizedStringId(42),
                SkillId.LightningBolt => new LocalizedStringId(44),
                SkillId.Thunderstorm => new LocalizedStringId(46),
                SkillId.ColdBolt => new LocalizedStringId(48),
                SkillId.FrostDiver => new LocalizedStringId(50),
                SkillId.NapalmBeat => new LocalizedStringId(52),
                SkillId.SoulStrike => new LocalizedStringId(54),
                SkillId.SafetyWall => new LocalizedStringId(56),
                SkillId.StoneCurse => new LocalizedStringId(58),
                SkillId.IncSpRecovery => new LocalizedStringId(60),
                SkillId.EnergyCoat => new LocalizedStringId(62),
                SkillId.OwlEye => new LocalizedStringId(64),
                SkillId.VultureEye => new LocalizedStringId(66),
                SkillId.ImproveConcentration => new LocalizedStringId(68),
                SkillId.DoubleStrafe => new LocalizedStringId(70),
                SkillId.ArrowShower => new LocalizedStringId(72),
                SkillId.ArrowCrafting => new LocalizedStringId(74),
                SkillId.ArrowRepel => new LocalizedStringId(76),
                SkillId.EnlargeWeightLimit => new LocalizedStringId(78),
                SkillId.Discount => new LocalizedStringId(80),
                SkillId.Overcharge => new LocalizedStringId(82),
                SkillId.Pushcart => new LocalizedStringId(84),
                SkillId.Vending => new LocalizedStringId(86),
                SkillId.Mammonite => new LocalizedStringId(88),
                SkillId.Identify => new LocalizedStringId(90),
                SkillId.ChangeCart => new LocalizedStringId(92),
                SkillId.CartRevolution => new LocalizedStringId(94),
                SkillId.CrazyUproar => new LocalizedStringId(96),
                SkillId.DoubleAttack => new LocalizedStringId(98),
                SkillId.ImproveDodge => new LocalizedStringId(100),
                SkillId.Steal => new LocalizedStringId(102),
                SkillId.Hiding => new LocalizedStringId(104),
                SkillId.Envenom => new LocalizedStringId(106),
                SkillId.Detoxify => new LocalizedStringId(108),
                SkillId.SandAttack => new LocalizedStringId(110),
                SkillId.FindStone => new LocalizedStringId(112),
                SkillId.ThrowStone => new LocalizedStringId(114),
                SkillId.Backslide => new LocalizedStringId(116),
                SkillId.Ruwach => new LocalizedStringId(118),
                SkillId.Teleport => new LocalizedStringId(120),
                SkillId.WarpPortal => new LocalizedStringId(122),
                SkillId.Pneuma => new LocalizedStringId(124),
                SkillId.DemonBane => new LocalizedStringId(126),
                SkillId.DivineProtection => new LocalizedStringId(128),
                SkillId.SignumCrucis => new LocalizedStringId(130),
                SkillId.Angelus => new LocalizedStringId(132),
                SkillId.Blessing => new LocalizedStringId(134),
                SkillId.AquaBenedicta => new LocalizedStringId(136),
                SkillId.Heal => new LocalizedStringId(138),
                SkillId.Cure => new LocalizedStringId(140),
                SkillId.IncreaseAgi => new LocalizedStringId(142),
                SkillId.DecreaseAgi => new LocalizedStringId(144),
                SkillId.HolyLight => new LocalizedStringId(146),
                _ => LocalizedStringId.INVALID,
            };
        }
    }
}
